# Base image
FROM ubuntu:24.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Update and install development tools and libraries
RUN apt-get update && apt-get install -y \
    build-essential \
    g++ \
    cmake \
    libsfml-dev \
    libtbb-dev \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /workspace
